### ISSUE TITLE
Arranging a Introductory hands-on workshop on K8S for beginner- Pune

### ISSUE THREAD

**Issue by anandbhagwat** [vishal-biyani/kubernetes-cncf-pune#1]
Hi Team,

I am nebiew in kubernetes and wanted to explore it. Together with me there are many people who want to learn K8S. Can this team arrange a basic workshop session on Kubernetes?

**Comment by yadavrn** [comment]
+ 1 for basic hands-on session

**Comment by vadasambar** [comment]
Hey @anandbhagwat , we have had beginner sessions in the past. Last one was in the last month's meetup (April 2020). If you want sessions around any particular topic, please go ahead and open another issue. 
Otherwise, we can close this issue.

**Comment by abhiniveshjain** [comment]
For K8s for newbies, you can attend the sessions that I am taking as part of AWS UG Pune. 

Part 1 is already done and recording is available at https://www.youtube.com/watch?v=bMS60RzPTIE&feature=youtu.be 

In next session, I will be primarily covering K8s concepts along with live Demos.  Session details will be published in https://www.meetup.com/puneawsug/ soon.
