### ISSUE TITLE
Proposal for November 2020 Meetup on Backup & Restore using Velero

### ISSUE THREAD

**Issue by sagar-jadhav** [vishal-biyani/kubernetes-cncf-pune#10]
**Proposal:**
- Introduction to Velero
- Velero architecture
- Velero Installation
- Backup & Restore
- Periodic Backup
- Difference use cases such as Migration, Disaster Recovery
- May be some realtime scenarios we can cover and the challenges faced so far
- Strategies for protecting Cloud native resources
- Stateless resources vs stateful
- Demo

**Speakers:**

Amitabh Prasad
Architect, Hybrid Cloud Team, IBM
https://www.linkedin.com/in/amitabh-prasad-22a44a3/

Sudhir Mohanty
Test Engineer, IBM
https://www.linkedin.com/in/sudhir-mohanty-022bb0149/

Sagar Jadhav
Backend Developer, IBM
https://www.linkedin.com/in/sagarjadhv23/

**Comment by sagar-jadhav** [comment]
Hello @vishal-biyani any update on the proposal? let me know if you need any additional details.

**Comment by vishal-biyani** [comment]
Hey @sagar-jadhav I am sorry for dropping the ball on this one. October turned out crazy with a few things. We can schedule this after Diwali - last week of November. I will find a date that works by Friday and respond on this issue. Appreciate your patience and sorry again!

**Comment by sagar-jadhav** [comment]
Thank you @vishal-biyani. Our preferable date is 28th November 2020 (Saturday).

**Comment by vishal-biyani** [comment]
Hey @sagar-jadhav By any chance 21st Nov works for you?

**Comment by sagar-jadhav** [comment]
Sorry, @vishal-biyani 21st won't work for me as I will be on Diwali vacation at that time.

**Comment by sagar-jadhav** [comment]
Sorry, @vishal-biyani 21st won't work for me as I will be on Diwali vacation at that time.

**Comment by vishal-biyani** [comment]
Hey @sagar-jadhav Confirming the 28 Nov, will announce the meetup in a bit.

**Comment by sagar-jadhav** [comment]
@vishal-biyani Sorry one of the presenters is not available on 28th Nov. Can you please schedule a meetup on 12th Dec?

Apologies for the inconvenience.
