### ISSUE TITLE
April 2020 Meetup

### ISSUE THREAD

**Issue by vadasambar** [vishal-biyani/kubernetes-cncf-pune#3]
Thread for discussion around April meetup.

**UPDATED**

**Speaker 1: Vivek Singh**

**Title: Writing application for Kubernetes**
When we say Kubernetes is an open source project that helps us orchestrate the containers, people who are new to this field or who have just started learning about get really confused about this, in this session I am planning to cover architecture level overview of Kubernetes as well has how to use its resources (ConfigMaps, Services, Deployments and other controllers) to get your app deployed on Kubernetes.
A part from that I will also be discussing about the how to go about resolving a problem that you are facing on your cluster, for example if a pod is not scheduled on a node etc.

**Bio**
I am a Software Developer at InfraCloud technologies, and have been working on Kubernetes and related technologies for some time now. I have also tried my hands into serverless world on top of Kubernetes and now a days exploring data backup and recovery of stateful application that are deployed on Kubernetes.

https://viveksingh.dev/

**Time**: 70-80 minutes.

---
**Speaker 2: Abhinivesh Jain**

**Topic: Launching Windows VM using KubeVirt & Openshift**

**Description about the topic-**
KubeVirt is an open-source project that offers you a VM-based virtualization option on top of any Kubernetes cluster. Lots of work happened in this area in the last couple of years, and Kubevirt is reaching the maturity stage to become production-ready. In this session, we will see how to deploy Kubevirt in Openshift Container Platform (OCP) 4.2 and get your first windows VM up and running inside OCP.

**Bio-**
Abhinivesh Jain is working as Edge Platform Lead in CIS-CTO organization in Wipro. He is an Author, blogger and frequent speaker in various industry forums. He has expertise in Cloud and Datacenter transformation, 5G and Edge Computing. Currently he is actively participating in KNI Edge Stack implementation and enhancements.

**Time required**
60 minutes

https://in.linkedin.com/in/abhiniveshjain
https://twitter.com/abhiniveshjain

**Comment by vadasambar** [comment]
Many folks have raised concern over meeting face to face for meetup because of the recent [COVID-19](https://www.who.int/emergencies/diseases/novel-coronavirus-2019) aka novel Coronavirus problem. 

We can think of shifting April meetup to a completely online conference call instead of actually meeting at a venue.

**Comment by viveksinghggits** [comment]
Hey @vadasambar,
Are we planning to have any Kubernetes for beginner kind of session in near future. I would like talk about that where we can discuss about some resources that we primarily use in Kubernetes would be intended for people who are starting with or want to start working with Kubernetes.

**Comment by vadasambar** [comment]
Hey @viveksinghggits , sorry for the delay! 
I think that's a great idea but I believe we might have had beginner sessions in the past.

@gauravgahlot , @vishal-biyani , what do you guys think about this?

**Comment by vishal-biyani** [comment]
@vadasambar So for beginner sessions - we do it from time to time as there are always new people looking to learn basics.

**Comment by gauravgahlot** [comment]
I think it would be nice to start with the basics again. We can record the sessions this time. This will encourage the beginners to join the meetup and we will have a consistent audience over time.

**Comment by vatsalparekh** [comment]
+1 for Beginner session

I would like to share about 'Design Patterns for managing VMs with Kubernetes' (not just a intro to KubeVirt which I shared in one of the meetup last year)
Maybe in this or upcoming meetups

Also, if we want to try a different venue at Red Hat office in Magarpatta, I would be interested to help and coordinate that

**Comment by bhavin192** [comment]
How about having a balance between beginner friendly sessions and normal/advance topics? This will make sure that the meetup is beneficial to both beginners and regular attendees. 
We can try to have one introductory sessions and one advance topic in every meetup?

Second option is to have 101 sessions now and then. Twice a year or so.

**Comment by vadasambar** [comment]
@vishal-biyani , @gauravgahlot , thank you for your thoughts! 
The way I see things, I think we can have @viveksinghggits 's session in the upcoming meetup. 

@vatsalparekh , thank you for your thoughts! 

>I would like to share about 'Design Patterns for managing VMs with Kubernetes' (not just a intro to KubeVirt which I shared in one of the meetup last year)

That would be awesome :)

>Also, if we want to try a different venue at Red Hat office in Magarpatta, I would be interested to help and coordinate that

That would be great. We can consider Red Hat as location in the upcoming meetups. That way we can cater to audience around that part of the city. As for the upcoming meetup I am of the opinion to go for a hangout/zoom meetup online. Let me know if you'd be interested in talking in the upcoming meetup!

**Comment by vadasambar** [comment]
@bhavin192 , makes sense. 

> We can try to have one introductory sessions and one advance topic in every meetup?

@bhavin192 , I think that's a good idea. Depending on how many CFPs we get we can align ourselves to this thought. If we get more than 2 CFPs, we can go for one beginner and one advance session to cater to a wider audience.  

>Second option is to have 101 sessions now and then. Twice a year or so.

I think this is what we have been doing. I think this is a good idea as well.

**Comment by vadasambar** [comment]
With the way the situation is worsening everyday I wonder if we should have a meetup at all next month? 
I think we can still have an online meetup but I am split on this. 
What do you guys think?

**Comment by bhavin192** [comment]
Let's keep the rhythm and have an online meetup? 
Last weekend some of the Python communities had online meetups. https://twitter.com/vipulgupta2048/status/1241071265017782272

Doing Zoom/Google Meet or even YouTube live is possible (using OBS)

**Comment by vadasambar** [comment]
@viveksinghggits and @vatsalparekh , would you guys be interested in speaking at this month's meetup? We will have the meetup online.

**Comment by viveksinghggits** [comment]
Hi @vadasambar 
yes I had a conversation with @gauravgahlot about this and I would like talk in this one.

**Comment by vadasambar** [comment]
Hey @viveksinghggits , awesome!  Can you provide some details of your talk in the following format:

- Topic
- Description about the topic
- Bio
- Time required
- Your social media links (twitter, github, linkedin etc.,)

[Here](https://github.com/kubernetes-pune/kubernetes-cncf-pune/issues/2#issuecomment-592351627)'s a good example you can refer to. 

We are thinking of having the meetup on 25th(Sat) or 26th(Sun) of this month.

**Comment by bhavin192** [comment]
Should we switch to one issue per talk proposal?

**Comment by vadasambar** [comment]
I think we can see how this one goes and try out separate issue for each proposal if it becomes difficult to follow what is happening in a single issue.

**Comment by abhiniveshjain** [comment]
I can take Kubernetes masterclass for beginners. (2 hrs with lots of hands-on) or session on running kubevirt on openshift

**Comment by vadasambar** [comment]
Hey @abhiniveshjain :) Thank you for showing interest in talking at this month's meetup. 

I think 2hrs might be a bit long because we have @viveksinghggits's talk as well.
 
Would it be possible to divide the talk into two segments perhaps or if you have any other ideas around this, I am open to them as well. Or, we can also take the talk around Kubevirt or openshift. 

@viveksinghggits , how much time would you need for your talk?

**Comment by viveksinghggits** [comment]
@vadasambar I am going to take almost 70-80 Mins.

**Comment by abhiniveshjain** [comment]
Ok. If time is constraint here then I will take Kubevirt on Openshift topic. It will take 45 min or so.

**Comment by vatsalparekh** [comment]
> @viveksinghggits and @vatsalparekh , would you guys be interested in speaking at this month's meetup? We will have the meetup online.

Sure! I can show about Kubevirt

**Comment by vadasambar** [comment]
@abhiniveshjain and @vatsalparekh , looks like your topics are overlapping. 

Would any one of you like to switch the topic to something else and we can have one of you talk at this month's meetup and one of you for the next month's meetup (we can reserve a speaker spot for the next month's meetup). 

Another option can be, you guys can present together and I will see how we could facilitate collaboration on that.

**Comment by vadasambar** [comment]
> @vadasambar I am going to take almost 70-80 Mins.

@viveksinghggits , alright! I will make arrangements for a 70-80 minutes of video call. 
Also, could you share the information around your talk in the prescribed format by the end of this week so that we can publish it on meetup as well

**Comment by vadasambar** [comment]
@vatsalparekh , @abhiniveshjain , if you guys want to talk it over zoom or anything, I can schedule a call and we can discuss how to go about this.

**Comment by abhiniveshjain** [comment]
Sure. Let's discuss. I am free now or anytime tomorrow.

**Comment by vatsalparekh** [comment]
@abhiniveshjain maybe you can do the intro / running kubevirt on openshift this time, and I can continue in next meetup with little more details

**Comment by abhiniveshjain** [comment]
sure @vatsalparekh.

**Comment by viveksinghggits** [comment]
Hey @vadasambar,
Below are the details of my talk that I planned, please let me know your views on this 

**Title: Writing application for Kubernetes**
When we say Kubernetes is an open source project that helps us orchestrate the containers, people who are new to this field or who have just started learning about get really confused about this, in this session I am planning to cover architecture level overview of Kubernetes as well has how to use its resources (ConfigMaps, Services, Deployments and other controllers) to get your app deployed on Kubernetes. 
A part from that I will also be discussing about the how to go about resolving a problem that you are facing on your cluster, for example if a pod is not scheduled on a node etc.


**Bio**
I am a Software Developer at InfraCloud technologies, and have been working on Kubernetes and related technologies for some time now. I have also tried my hands into serverless world on top of Kubernetes and now a days exploring data backup and recovery of stateful application that are deployed on Kubernetes.

viveksingh.dev 

Time: 70-80 minutes.

**Comment by vadasambar** [comment]
@abhiniveshjain , can you provide details for your talk in the following format: https://github.com/kubernetes-pune/kubernetes-cncf-pune/issues/3#issuecomment-611547291

**Comment by vadasambar** [comment]
> Hey @vadasambar,
> Below are the details of my talk that I planned, please let me know your views on this
> 
> **Title: Writing application for Kubernetes**
> When we say Kubernetes is an open source project that helps us orchestrate the containers, people who are new to this field or who have just started learning about get really confused about this, in this session I am planning to cover architecture level overview of Kubernetes as well has how to use its resources (ConfigMaps, Services, Deployments and other controllers) to get your app deployed on Kubernetes.
> A part from that I will also be discussing about the how to go about resolving a problem that you are facing on your cluster, for example if a pod is not scheduled on a node etc.
> 
> **Bio**
> I am a Software Developer at InfraCloud technologies, and have been working on Kubernetes and related technologies for some time now. I have also tried my hands into serverless world on top of Kubernetes and now a days exploring data backup and recovery of stateful application that are deployed on Kubernetes.
> 
> viveksingh.dev
> 
> Time: 70-80 minutes.

Looks good to me @viveksinghggits !

**Comment by abhiniveshjain** [comment]
@vadasambar, Here you go.

Topic
Launching Windows VM using KubeVirt & Openshift

Description about the topic-
KubeVirt is an open-source project that offers you a VM-based virtualization option on top of any Kubernetes cluster. Lots of work happened in this area in the last couple of years, and Kubevirt is reaching the maturity stage to become production-ready. In this session, we will see how to deploy Kubevirt in Openshift Container Platform (OCP) 4.2 and get your first windows VM up and running inside OCP.

Bio- 
Abhinivesh Jain is working as Edge Platform Lead in CIS-CTO organization in Wipro. He is an Author, blogger and frequent speaker in various industry forums. He has expertise in Cloud and Datacenter transformation, 5G and Edge Computing. Currently he is actively participating in KNI Edge Stack implementation and enhancements.

Time required
60 minutes

Your social media links (twitter, github, linkedin etc.,)

https://in.linkedin.com/in/abhiniveshjain
https://twitter.com/abhiniveshjain

**Comment by vadasambar** [comment]
Thanks @abhiniveshjain ! :smile:

**Comment by vadasambar** [comment]
Great talk @viveksinghggits and @abhiniveshjain ! 

Are you guys okay with the video recording being public? 
@abhiniveshjain , you have Wipro's logo in your deck. Just wanted to know if that would be an issue. 

Also, can you guys also share the slide deck? Maybe raise a PR to this repo or just mail me.

**Comment by abhiniveshjain** [comment]
That's fine, you can make video recording public. My article covers more that I presented so I would suggest to publish this.
https://dzone.com/articles/kubevirt-in-action

**Comment by vadasambar** [comment]
Alright. Thank you @abhiniveshjain !
