### ISSUE TITLE
Proposal for joint virtual meetup.

### ISSUE THREAD

**Issue by VineethReddy02** [vishal-biyani/kubernetes-cncf-pune#5]
Hi!

I am one of the co-organizers for the[ CNCF Hyderabad ](https://www.meetup.com/Cloud-Native-Hyderabad/)meetup group. 
I think it would be a great idea to do a joint virtual meetup between Pune and Hyderabad communities in the upcoming month i.e June. 

@vishal-biyani

**Comment by vadasambar** [comment]
@VineethReddy02 , that sounds great!

**Comment by abhiniveshjain** [comment]
Good Idea. As long as it is happening virtually, there is no need to restrict it for given city.

**Comment by VineethReddy02** [comment]
Thanks for echoing the proposal. The CNCF Hyderabad meetup group and Hashicorp user group are doing a joint virtual event in June. We can definitely do one in July. If possible. 

Thanks!

**Comment by vishal-biyani** [comment]
Closing for now, let's open a new one for future
