### ISSUE TITLE
Proposal for community partner for Cloud Community Days

### ISSUE THREAD

**Issue by CodeOpsTechnologies** [vishal-biyani/kubernetes-cncf-pune#6]
Hi Vishal & Team, 

As discussed, please share your logo (or let us know so we can proceed) to make your meetup group (https://www.meetup.com/Kubernetes-Pune) a community partner for Cloud Community Days (CCDays.konfhub.com)

For community partner the gives and takes:

As a community partner, here's what can be expected from our end:
1. Promotion of your meetup group on our social media channels and website as a community partner. On click of the community logo, it will redirect to their community / meetup page

Here's what we need from community partner:
1. Having the event announced on your meetup page and send mailers to the meetup group or Telegram/Slack/Whatsapp channel

**Comment by vadasambar** [comment]
@CodeOpsTechnologies , sounds great!
If you need anything related to the logo (bigger size), please let me know :D

**Comment by gauravgahlot** [comment]
Since the ground is set, maybe we can close this issue. @vadasambar
