### ISSUE TITLE
June 2020 Meetup

### ISSUE THREAD

**Issue by gauravgahlot** [vishal-biyani/kubernetes-cncf-pune#7]
Thread for June 2020 Meetup.

**What is this for?**
This is a thread for discussion around
 - the upcoming meetup 
 - Call for Proposal (CFP) 
If you want to give a talk at the meetup, this is the right place to show your interest. 

_Note:_
 - Available slots - 2 
 - Decision based on - FCFS and topic

**Comment by gauravgahlot** [comment]
@VineethReddy02 Maybe it's time. :)
ref: https://github.com/kubernetes-pune/kubernetes-cncf-pune/issues/5

**Comment by VineethReddy02** [comment]
@gauravgahlot 
We already announced the meetup on June 20 in collaboration with the hashicorp-user-group.
Maybe we can do the joint event in the upcoming meetup. Updated the same in the issue I raised. :)

**Comment by vadasambar** [comment]
Meetup concluded: https://www.meetup.com/Kubernetes-Pune/events/270782775/

**Comment by vadasambar** [comment]
@gauravgahlot , @VineethReddy02 can we close this issue and continue our discussion at #8 ?
