### ISSUE TITLE
Proposal for October 2020 Meetup

### ISSUE THREAD

**Issue by join2ashish** [vishal-biyani/kubernetes-cncf-pune#9]
**Title**: Flatcar Linux, Beyond CoreOS Legacy
**Abstract**: This talk will introduce Flatcar Container Linux which is an immutable Linux distribution for containers. It is a friendly fork of the now retired and no longer commercially supported CoreOS Container Linux. It’s fully compatible with CoreOS and can act as a drop-in replacement. This presentation will also cover what makes Flatcar Container Linux unique, address compatibility concerns and talk about new features that go beyond CoreOS. In the end, the audience should come away with answers to most of the “what”s, “why”s and “how”s of Flatcar Container Linux.

**_Speaker Details_**

**Speaker Name**: Sayan Chowdhury
**Desgination**: Software Engineer at Kinvolk 
**Bio**: Sayan started his career at HackerEarth back in 2013, joining as the first engineer on the team. He has been a long-time contributor to the Fedora Project, working on projects maintained by the Fedora Infrastructure team, and later joining the Fedora team at Red Hat in 2015 to contribute full time. As a part of the team, he worked with building projects to support the Fedora Atomic release pipeline. He was also responsible for maintaining the pipeline for the Fedora images on various cloud providers. Later, Sayan moved to the Red Hat CoreOS team, to work on releasing Fedora CoreOS. Sayan has moved through various domains, from desktop, to web to systems and loving settling with systems

**Preferred Date**: Any date after 6th Oct. 

**_Greetings_**

Hello Team,

I’m Ashish Mishra, Events Coordinator at Kinvolk. I came across your Meetup group and thought that it would align with some interesting things we are doing at our company. 

Our company Kinvolk is one of the most trusted companies in the cloud native space. We build open-source products and provide open source engineering services. We have a team full of experts in various technologies like cloud native, Kubernetes, and down through the container runtimes, systemd, and the Linux kernel. 

I’m curious to know if you are planning to take your meetup to the virtual space and if you would be interested in having one of our speakers at your event.

Looking forward to hearing from you. 

Thanks & Regards
Ashish Mishra
**Email**: ashish@kinvolk.io

**Comment by vishal-biyani** [comment]
Hey, @join2ashish Thanks - give me a couple of days and I will share when can we do a meetup in October.

**Comment by join2ashish** [comment]
Thanks @vishal-biyani much appreciated :)

**Comment by join2ashish** [comment]
Hey, @vishal-biyani waiting for your response. Looking forward to hearing from your.

**Comment by vishal-biyani** [comment]
Hey @join2ashish I am sorry for dropping the ball on this one. October turned out crazy with a few things. We can schedule this after Diwali - last week of November. I will find a date that works by Friday and respond on this issue. Appreciate your patience and sorry again!

**Comment by vishal-biyani** [comment]
Hey @join2ashish Would 28 Nov Sat morning work for you folks?

**Comment by join2ashish** [comment]
Hey, @vishal-biyani Sayan is asking for 21st Nov. Is this possible?

**Comment by vishal-biyani** [comment]
Hey @join2ashish Sorry, 21st did not work as there are other conflicts. We can do 28 or 18 December, which one you want to shoot for?

**Comment by sayanchowdhury** [comment]
Hi Vishal, Happy New Year :) Can we do the talk this month between 25th-29th January?

**Comment by vishal-biyani** [comment]
Hey, @sayanchowdhury Happy new year! I think 29th Jan is doable - but will have to do it in the evening (~6 PM IST), would that work for you?

**Comment by sayanchowdhury** [comment]
@vishal-biyani 29th Jan, 6PM works for me.

**Comment by vishal-biyani** [comment]
@sayanchowdhury One last request for change - would 28 work instead of 29 for you?

**Comment by sayanchowdhury** [comment]
Sure, works for me.

**Comment by vishal-biyani** [comment]
Thanks @sayanchowdhury , published here: https://www.meetup.com/Kubernetes-Pune/events/275846652

**Comment by sayanchowdhury** [comment]
Thanks @vishal-biyani for giving me the opportunity to talk at the meetup. I had a great experience. Hope to come back soon to give a talk on another topic.

**Comment by vishal-biyani** [comment]
Thanks @sayanchowdhury For your time and insightful talk. Looking forward to having you again soon at K8S Pune Meetup!
